### ISSUE TITLE
Confusing info / Migration error

### ISSUE THREAD

**Issue by KFad11** [learn-co-curriculum/phrg-mechanics-of-migrations#2]
When the lab gets to the part about Creating a table, and running the migrate command, "it's time to run rake db:migrate". The lab throws the error "StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:". Needing to add the version of the framework to the Migration was necessary but not explained. Also around that point there's a lot of info that's not needed to pass the tests. I was passing all the tests around that section of the lab but there's still a lot of material left in there that doesn't seem to be needed. Mainly after the phrase "Try Out The Following:
Check that the class exists:"

@garettarrowood

**Comment by garettarrowood** [comment]
Addressed in 9729fbe01b880ccadbbda5cab2888f8973475ad5 .
